### ISSUE TITLE
[enhancement] setup github actions for CI/CD

### ISSUE THREAD

**Issue by Quadriphobs1** [Quadriphobs1/stopwatch#10]
Currently the project uses circle ci for CI/CD but it would be great to actually use github actions workflow to handle test, building and release

**Comment by Bhavesh27** [comment]
i would like to work on it but currently Only repository collaborators can create workflows.

**Comment by Quadriphobs1** [comment]
Hey @techieashish  In order to test if the workflow work fine I need to merge it first however, the workflow build fails to install yarn can you use https://github.com/Borales/actions-yarn Also @Bhavesh27 it's fine you can clone the repo, and create a pull request for this.
